// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzN-CS6uhDBwlmcjTSqLasnAvVWmbdJWg',
    appId: '1:409331129900:web:5268f46e4c9455c1defb89',
    messagingSenderId: '409331129900',
    projectId: 'mentisia-247a6',
    authDomain: 'mentisia-247a6.firebaseapp.com',
    storageBucket: 'mentisia-247a6.firebasestorage.app',
    measurementId: 'G-CM3QRPFKMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSc-5nRKIYFwxQdfF8sbCi9x5LnStTv0A',
    appId: '1:409331129900:android:c9380035ef37e2f6defb89',
    messagingSenderId: '409331129900',
    projectId: 'mentisia-247a6',
    storageBucket: 'mentisia-247a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6mjlvfKqJy2SuBGrjDLUzmSF6V9Eryhw',
    appId: '1:409331129900:ios:645b61681a36da53defb89',
    messagingSenderId: '409331129900',
    projectId: 'mentisia-247a6',
    storageBucket: 'mentisia-247a6.firebasestorage.app',
    iosBundleId: 'com.example.mentisAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6mjlvfKqJy2SuBGrjDLUzmSF6V9Eryhw',
    appId: '1:409331129900:ios:645b61681a36da53defb89',
    messagingSenderId: '409331129900',
    projectId: 'mentisia-247a6',
    storageBucket: 'mentisia-247a6.firebasestorage.app',
    iosBundleId: 'com.example.mentisAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzN-CS6uhDBwlmcjTSqLasnAvVWmbdJWg',
    appId: '1:409331129900:web:3f40339642bbbfc5defb89',
    messagingSenderId: '409331129900',
    projectId: 'mentisia-247a6',
    authDomain: 'mentisia-247a6.firebaseapp.com',
    storageBucket: 'mentisia-247a6.firebasestorage.app',
    measurementId: 'G-L3WNYBHE3R',
  );
}
