// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint

// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
// // import 'package:flutter_dotenv/flutter_dotenv.dart';

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//       // return android;
//       case TargetPlatform.iOS:
//       // return ios;
//       case TargetPlatform.macOS:
//       // return macos;
//       case TargetPlatform.windows:
//       // return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   // /// WEB
//   static final FirebaseOptions web = FirebaseOptions(
//     apiKey: dotenv.env['GOOGLE_WEB_API_KEY'] ?? '',
//     appId: '1:409331129900:web:5268f46e4c9455c1defb89',
//     messagingSenderId: '409331129900',
//     projectId: 'mentisia-247a6',
//     authDomain: 'mentisia-247a6.firebaseapp.com',
//     storageBucket: 'mentisia-247a6.firebasestorage.app',
//     measurementId: 'G-CM3QRPFKMN',
//   );

//   /// ANDROID
//   static final FirebaseOptions android = FirebaseOptions(
//     apiKey: dotenv.env['GOOGLE_ANDROID_API_KEY'] ?? '',
//     appId: '1:409331129900:android:c9380035ef37e2f6defb89',
//     messagingSenderId: '409331129900',
//     projectId: 'mentisia-247a6',
//     storageBucket: 'mentisia-247a6.firebasestorage.app',
//   );

//   /// iOS
//   static final FirebaseOptions ios = FirebaseOptions(
//     apiKey: dotenv.env['GOOGLE_IOS_API_KEY'] ?? '',
//     appId: '1:409331129900:ios:645b61681a36da53defb89',
//     messagingSenderId: '409331129900',
//     projectId: 'mentisia-247a6',
//     storageBucket: 'mentisia-247a6.firebasestorage.app',
//     iosBundleId: 'com.example.mentisAi',
//   );

//   /// macOS (usa o mesmo do iOS)
//   static final FirebaseOptions macos = FirebaseOptions(
//     apiKey: dotenv.env['GOOGLE_IOS_API_KEY'] ?? '',
//     appId: '1:409331129900:ios:645b61681a36da53defb89',
//     messagingSenderId: '409331129900',
//     projectId: 'mentisia-247a6',
//     storageBucket: 'mentisia-247a6.firebasestorage.app',
//     iosBundleId: 'com.example.mentisAi',
//   );

//   /// Windows
//   static final FirebaseOptions windows = FirebaseOptions(
//     apiKey: dotenv.env['GOOGLE_WINDOWS_API_KEY'] ?? '',
//     appId: '1:409331129900:web:3f40339642bbbfc5defb89',
//     messagingSenderId: '409331129900',
//     projectId: 'mentisia-247a6',
//     authDomain: 'mentisia-247a6.firebaseapp.com',
//     storageBucket: 'mentisia-247a6.firebasestorage.app',
//     measurementId: 'G-L3WNYBHE3R',
//   );
// }
